config/routes.rb
Rails.application.routes.draw do

  namespace :admin do
    resources :events, path: 'eventos' do
      patch :add_subscription
    end
    resources :contacts, path: 'contactos'
    root 'admin#login'
  end

  get '/inscripcion/:event_id', to: 'subscription#subscribe', as: :subscription
  resources :subscription, except: :all do
    post :submit, on: :collection
    post :toggle_assistance, on: :member
  end
  #post '/subscription/submit', to: 'subscription#submit', as: :submit_subscription
  get 'success', to: 'application#success', as: :success
  root 'application#home'
end

app/models/contact.rb
class Contact < ActiveRecord::Base
  has_many :subscriptions
  has_many :events, through: :subscriptions
  validates :email, presence: true

  def to_s
    "#{first_name} #{last_name}"
  end
end

app/models/event.rb
class Event < ActiveRecord::Base

  MAX_SLUG_LENGTH = 240
  has_many :participations
  has_many :subscriptions
  enum state: [:draft, :open, :closed]
  validates :name, :state, :start_date, :start_time, presence: true
  before_create :set_slug
  accepts_nested_attributes_for :subscriptions, allow_destroy: true

  protected
    def set_slug
      self.slug = name.parameterize + "-#{I18n.l(start_date)}" if slug.blank?
      self.slug = slug.truncate(MAX_SLUG_LENGTH, omission: '', separator: '-') if slug.length > MAX_SLUG_LENGTH
    end
end

app/models/participation.rb
class Participation < ActiveRecord::Base
  belongs_to :user
  belongs_to :event
end

app/models/subscription.rb
class Subscription < ActiveRecord::Base
  belongs_to :contact
  belongs_to :event

  validates :contact, :event, presence: true
  validates :contact, uniqueness: { scope: :event_id }
end

app/models/subscription_form.rb
class SubscriptionForm

  include ActiveModel::Model

  attr_accessor :event_id, :email, :first_name, :last_name
  validates :email, :first_name, :last_name, :event_id, presence: true

  def submit
    contact = Contact.find_or_create_by(email: email) do |new_contact|
      new_contact.first_name = first_name
      new_contact.last_name  = last_name
    end

    subscription = contact.subscriptions.create(event_id: event_id)
    subscription.persisted?
  end

end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :participations
  has_many :events
end

app/controllers/admin/admin_controller.rb
class Admin::AdminController < ApplicationController

  def login
    render layout: 'simple'
  end
end

app/controllers/admin/contacts_controller.rb
class Admin::ContactsController < Admin::AdminController
  before_action :set_contact, only: [:show, :edit, :update, :destroy]

  def index
    @contacts = Contact.all
  end

  def show
  end

  def new
    @contact = Contact.new
  end

  def edit
  end

  def create
    @contact = Contact.new(contact_params)
    if @contact.save
      redirect_to [:admin, @contact], notice: t(:created)
    else
      render :new
    end
  end

  def update
    if @contact.update(contact_params)
      redirect_to [:admin, @contact], notice: t(:updated)
    else
      render :edit
    end
  end

  def destroy
    @contact.destroy
    redirect_to [:admin, :contacts], notice: t(:deleted)
  end

  private
    def set_contact
      @contact = Contact.find(params[:id])
    end

    def contact_params
      params.require(:contact).permit(:email, :first_name, :last_name)
    end
end

app/controllers/admin/events_controller.rb
class Admin::EventsController < Admin::AdminController

  def index
    @events = Event.all
  end

  def new
    @event = Event.new
    @event.subscriptions.build
  end

  def show
    @event = Event.find params[:id]
  end

  def edit
    @event = Event.find params[:id]
  end

  def create
    @event = Event.new(event_params)
    if @event.save
      flash[:success] = t(:created)
      redirect_to [:admin, @event]
    else
      flash[:danger] = t(:failed)
      render 'new'
    end
  end

  def update
    @event = Event.find params[:id]
    if @event.update(event_params)
      flash[:success] =  t(:updated)
      redirect_to [:admin, @event]
    else
      flash[:danger] =  t(:failed)
      render 'edit'
    end
  end

  def destroy
    @event = Event.find params[:id]
    @event.destroy
  end

  def add_subscription
    throw params
  end

  private
  def event_params
    params.require(:event).permit(:name, :description, :start_date, :start_time)
  end
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < Admin::AdminController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  def index
    @users = User.all
  end

  def show
  end

  def new
    @user = User.new
  end

  def edit
  end

  def create
    @user = User.new(user_params)
    if @user.save
      redirect_to [:admin, @user], notice: t(:success)
    else
      render :new
    end
  end

  def update
    if @user.update(user_params)
      redirect_to [:admin, @user], notice: t(:success)
    else
      render :edit
    end
  end

  def destroy
    @user.destroy
    redirect_to [:admin, :users], notice: t(:success)
  end

  private
    def set_user
      @user = User.find(params[:id])
    end

    def user_params
      params.require(:user).permit(:email, :first_name, :last_name, :role)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  add_flash_types :success, :info, :warning, :danger

  def home
  end

end

app/controllers/subscription_controller.rb
class SubscriptionController < ApplicationController

  layout 'simple'

  def subscribe
    @event = Event.find_by slug: params[:event_id]
    @form = SubscriptionForm.new(event_id: @event.id)
  end

  def submit
    @form = SubscriptionForm.new form_params
    if @form.submit
      redirect_to success_path
    else
      @event = Event.find @form.event_id
      flash[:danger] = t(:subscription_failed)
      render :subscribe
    end
  end

  def toggle_assistance
    @subscription = Subscription.find(params[:id])
    @subscription.toggle!(:assistance)
    flash[:success] = t(:success)
    render 'show_flash' #nothing: true
  end

  def success
    #TODO: Subscriptions in their own folder with success view.
  end

  def form_params
    params.require(:subscription_form).permit(:event_id, :email, :first_name, :last_name)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper

  def flash_message(klass, message)
    klass = 'success' if klass == 'notice' || klass == 'alert'
    flash.discard(klass)
    content_tag :span, nil, class: "flash-alert flash-alert-#{klass}", data: {toggle: :snackbar, content: message}
  end

  def flash_messages
    flash.map do |type, message|
      flash_message(type, message)
    end.join.html_safe
  end

  def icon(name, html_options={})
    html_options[:class] = ['fa', "fa-#{name}", html_options[:class]].compact
    content_tag(:i, nil, html_options)
  end

  def facebook_url
    'https://www.facebook.com/activismo.coala'
  end

  def section(name)
    partial = File.join('application', 'home', name)
    content_tag :section, id: name, class: 'home-section' do
      content_tag :div, class: :container do
        render partial
      end
    end
  end

  def earthlings_url
    'https://youtube.googleapis.com/v/PRrH6Ml5IDU'
  end

end

app/views/admin/admin/_aside.html.erb
<ul class="well nav nav-pills nav-stacked">
  <li><%= link_to t(:home), [:admin, :events], class: 'home-link' %></li>
  <li><%= link_to t(:events), [:admin, :events], class: 'event-link' %></li>
  <li><%= link_to t(:contacts), [:admin, :contacts], class: 'contact-link' %></li>
</ul>

app/views/admin/admin/_head.html.erb
<title><%= t :admin %></title>
<%= stylesheet_link_tag    'admin', media: 'all', 'data-turbolinks-track' => true %>
<%= javascript_include_tag 'admin', 'data-turbolinks-track' => true %>
<%= javascript_include_tag :defaults, "nested_form" %>
<%= csrf_meta_tags %>

app/views/admin/admin/_navbar.html.erb
<div class="navbar navbar-default">
  <div class="navbar-header">
    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#navbar-collapse">
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
    </button>
    <%= link_to t(:admin), root_path, class: 'navbar-brand' %>
  </div>

  <div class="collapse navbar-collapse" id="navbar-collapse">
    <ul class="nav navbar-nav navbar-right">
      <%# if user_signed_in? %>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false"><%#= current_user.email %> <span class="caret"></span></a>
          <ul class="dropdown-menu" role="menu">
            <% unless @home %>
              <li><%= link_to t(:home), root_path, class: 'home-link' %></li>
              <li class="divider"></li>
            <% end %>
            <li><%#= link_to t(:logout), destroy_user_session_path, method: :delete, class: 'logout-link' %></li>
          </ul>
        </li>
      <%# end %>
    </ul>
  </div>
</div>

app/views/admin/admin/login.html.erb
<h1><%= t :login %></h1>

app/views/admin/contacts/_contact.html.erb
<%= link_to [:admin, contact], class: 'list-group-item' do %>
  <%= contact.last_name %> <%= contact.first_name %>
  <span class="small-note"><%= contact.email %></span>
<% end %>

app/views/admin/contacts/_form.html.erb
<%= form_for([:admin, @contact]) do |f| %>
  <% if @contact.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@contact.errors.count, "error") %> prohibited this contact from being saved:</h2>

      <ul>
      <% @contact.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <article class="form-group">
    <%= f.label :email %><br>
    <%= f.text_field :email, autofocus: true, class: 'form-control' %>
  </article>
  <article class="form-group">
    <%= f.label :first_name %><br>
    <%= f.text_field :first_name, class: 'form-control' %>
  </article>
  <article class="form-group">
    <%= f.label :last_name %><br>
    <%= f.text_field :last_name, class: 'form-control' %>
  </article>
  <article class="form-group">
    <%= submit_tag t(:submit), class: 'btn btn-primary' %>
  </article>
<% end %>

app/views/admin/contacts/edit.html.erb
<h1><%= t :contact, scope: :edit %></h1>

<section class="well"><%= render 'form' %></section>

app/views/admin/contacts/index.html.erb
<h1>
  <%= link_to t(:contact, scope: :new), [:new, :admin, :contact], class: 'pull-right btn btn-primary btn-add' %>
  <%= t :contacts %>
</h1>

<section id="contacts">
  <%= render @contacts %>
</section>

app/views/admin/contacts/new.html.erb
<h1><%= t :contact, scope: :new %></h1>

<section class="well"><%= render 'form' %></section>

app/views/admin/contacts/show.html.erb
<h1><%= t :contact %></h1>

<section class="well">

  <dl>
    <dt><%= t :email %></dt>
    <dd><%= @contact.email %></dd>

    <dt><%= t :first_name %></dt>
    <dd><%= @contact.first_name %></dd>

    <dt><%= t :last_name %></dt>
    <dd><%= @contact.last_name %></dd>

    <dt><%= t :created_at %></dt>
    <dd><%= l @contact.created_at %></dd>

    <dt><%= t :subscriptions %></dt>
    <dd>
      <ul>
      <% @contact.subscriptions.each do |subscription| %>
        <li>
          <%= subscription.event.name %>
          <%= subscription.assistance ? icon(:check, class: 'text-success') : icon(:times, class: 'text-danger') %>
        </li>
      <% end %>
      </ul>
    </dd>
  </dl>

  <%= link_to t(:contact, scope: :edit), [:edit, :admin, @contact], class: 'btn btn-edit btn-primary' %>
  <%= link_to t(:back), [:admin, :contacts], class: 'btn btn-back btn-link' %>

</section>

app/views/admin/events/_event.html.erb
<%= link_to [:admin, event], class: 'list-group-item' do %>
  <span class="label label-primary"><%= event.id %></span>
  <%= event.name %>
  <span class="badge">
    <strong>Slug:</strong>
    <%= event.slug %>
  </span>
<% end %>

app/views/admin/events/_form.html.erb
<%= nested_form_for [:admin, @event] do |f| %>

  <article class="form-group">
    <%= f.label :name %>
    <%= f.text_field :name, autofocus: true, class: 'form-control' %>
  </article>

  <div class="row">
    <div class="col-md-6">
      <article class="form-group">
        <%= f.label :start_date %>
        <%= f.date_field :start_date, class: 'form-control' %>
      </article>
    </div>

    <div class="col-md-6">
      <article class="form-group">
        <%= f.label :start_time %>
        <%= f.time_field :start_time, class: 'form-control' %>
      </article>
    </div>
  </div>

  <article class="form-group">
    <%= f.label :description %>
    <%= f.text_area :description, class: 'form-control' %>
  </article>

  <article class="form-group">
    <%= f.label :state, class: 'control-label' %>
    <%= f.select :state, options_for_select(Event.states.map {|k,v| [t(k),k]}), {}, {class: 'form-control'} %>
  </article>

  <article class="form-group">
    <%= submit_tag t(:submit), class: 'btn btn-primary' %>
  </article>

<% end %>

app/views/admin/events/edit.html.erb
<h1><%= t :event, scope: :edit %></h1>

<section class="well"><%= render 'form' %></section>

app/views/admin/events/index.html.erb
<h1>
  <%= link_to t(:event, scope: :new), [:new, :admin, :event], class: 'pull-right btn btn-primary btn-add' %>
  <%= t :events %>
</h1>

<section id="events">
  <%= render @events %>
</section>

app/views/admin/events/new.html.erb
<h1><%= t :event, scope: :new %></h1>

<section class="well"><%= render 'form' %></section>

app/views/admin/events/show.html.erb
<h1>
  <%= t :event %>
  <%= link_to t(:back), [:admin, :events], class: 'pull-right btn btn-back btn-link' %>
  <%= link_to t(:event, scope: :edit), [:edit, :admin, @event], class: 'pull-right btn btn-edit btn-primary' %>
</h1>
<section class="well">

  <dl>
    <dt><%= t :name %></dt>
    <dd><%= @event.name %></dd>

    <dt><%= t :start_date %></dt>
    <dd><%= l @event.start_date %></dd>

    <dt><%= t :start_time %></dt>
    <dd><%= l @event.start_time %></dd>

    <dt><%= t :description %></dt>
    <dd><%= @event.description %></dd>

    <dt><%= t :subscriptions %></dt>
    <dd>
      <ul class="list-group">
        <% @event.subscriptions.each do |subscription| %>
          <li class="list-group-item">
            <%= subscription.contact %>
            <% id = "subscription-#{subscription.id}"%>
            <%= link_to '',[:toggle_assistance, subscription], method: :post, remote: true, id: id %>
            <span class="togglebutton" onclick="document.getElementById('<%= id %>').click();">
              <label><%= tag :input, type: :checkbox, checked: subscription.assistance %></label>
            </span>
          </li>
        <% end %>
      </ul>
    </dd>

  </dl>

  <%= nested_form_for [:admin, @event], url: admin_event_add_subscription_path(@event) do |f| %>
    <%= f.fields_for :subscriptions, class: 'row' do |sf| %>
      <article class="form-group">
        <div class="row">
          <div class="col-xs-11">
            <%= sf.select :contact_id, options_for_select(Contact.all.map { |v| [v.email, v.id] }), {}, { class: 'form-control' } %>
          </div>
          <div class="col-xs-1">
            <%= sf.link_to_remove do %>
              <%= icon 'remove' %>
            <% end %>
          </div>
        </article>
      <% end %>
      <%= f.link_to_add :subscriptions do %>
        <%= icon 'user-plus' %>
      <% end %>

      <article class="form-group">
        <%= submit_tag t(:submit), class: 'btn btn-primary' %>
      </article>
    <% end %>

  </section>

app/views/admin/workshops/_form.html.erb
<%= form_for [:admin, @workshop] do |f| %>

  <article class="form-group">
    <%= f.label :title %>
    <%= f.text_field :title, class: 'form-control' %>
  </article>

  <div class="row">
    <div class="col-md-6">
      <article class="form-group">
        <%= f.label :start_date %>
        <%= f.date_field :start_date, class: 'form-control' %>
      </article>
    </div>

    <div class="col-md-6">
      <article class="form-group">
        <%= f.label :start_time %>
        <%= f.time_field :start_time, class: 'form-control' %>
      </article>
    </div>
  </div>

  <article class="form-group">
    <%= f.label :description %>
    <%= f.text_area :description, class: 'form-control' %>
  </article>

  <article class="form-group">
    <%= f.label :state, class: 'control-label' %>
    <%= f.select :state, options_for_select(Workshop.states.map {|k,v| [t(k),k]}), {}, {class: 'form-control'} %>
  </article>

  <article class="form-group">
    <%= submit_tag t(:submit), class: 'btn btn-primary' %>
  </article>

<% end %>

app/views/admin/workshops/edit.html.erb
<h1><%= t :workshop, scope: :edit %></h1>

<section class="well"><%= render 'form' %></section>

app/views/admin/workshops/new.html.erb
<h1><%= t :workshop, scope: :new %></h1>

<section class="well"><%= render 'form' %></section>

app/views/application/_analytics.html.erb
<script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-54380513-1', 'auto');
  ga('send', 'pageview');
</script>

app/views/application/_head.html.erb
<%= content_tag :title, t(:tag_title) %>
<%= stylesheet_link_tag "application", media: :all %>
<%= javascript_include_tag "application" %>
<%= favicon_link_tag %>
<%= csrf_meta_tags %>

<%= tag :meta, charset: "UTF-8" %>
<%= tag :meta, name: :author, content: "Nicanor Perera" %>
<%= tag :meta, name: :language, content: I18n.locale %>
<%= tag :meta, lang: I18n.locale, name: :description, content: 'Somos un grupo de activistas de la Ciudad de La Plata dedicado a la difusión del veganismo. COALA nació en Agosto de 2013, y a partir de entonces lucha sin descanso por la liberación animal.' %>

<%= render 'analytics' %>

app/views/application/_navbar.html.erb
<nav id="navbar" class="navbar navbar-default navbar-fixed-top scrollspy" role="navigation">
  <div class="container">

    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#navbar-collapse">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to t(:brand), '#cover', class: 'navbar-brand hidden-sm hidden-xs' %>
    </div>

    <nav id="navbar-collapse" class="collapse navbar-collapse" role="navigation">
      
      <ul class="nav navbar-nav">
        <li><%= link_to     t(:about), '#about' %></li>
        <li><%= link_to  t(:advocacy), '#advocacy' %></li>
        <li><%= link_to t(:diffusion), '#diffusion' %></li>
        <li><%= link_to   t(:cuisine), '#cuisine' %></li>
        <li><%= link_to     t(:radio), '#radio' %></li>
      </ul>

      <ul class="nav navbar-nav navbar-right">
        <li>
          <%= link_to facebook_url, target: '_blank', class: 'social' do %>
            <%= icon 'facebook-square fa-2x' %> <%= content_tag :span, t(:visit_facebook), class: 'hidden-sm hidden-xs' %>
          <% end %>
        </li>
      </ul>

    </nav><!-- /.navbar-collapse -->
  </div><!-- /.container -->
</nav>

app/views/application/home.html.erb
<section id="nav" >
  <%= render 'navbar' %>
</section>

<section id="top"></section>

<%= section 'cover' %>
<%= section 'about' %>
<%= section 'advocacy' %>
<%= section 'diffusion' %>
<%= section 'cuisine' %>
<%= section 'radio' %>

<span class="nav-scroll scrollspy hidden-sm hidden-xs">
  <ul class="nav list-unstyled">
    <% [:cover, :about, :advocacy, :diffusion, :cuisine, :radio].each do |section| %>
      <li><%= link_to icon(:circle), "##{section}", title: t(section) %></li>
    <% end %>
  </ul>
</span>

<span class="totop"><a href="#top"><i class="fa fa-angle-up"></i></a></span>

app/views/application/home/_about.html.erb
<div class="row">
  <div class="col-md-8">
    <header><h1><%= t :about %></h1></header>

    <p class="lead">Somos un grupo de activistas de la <strong>Ciudad de La Plata</strong> dedicado a la difusión del <strong>veganismo</strong>.
    <abbr title="Colectivo Abolicionista por la Liberación Animal">COALA</abbr> nació en Agosto de 2013, y a partir de entonces lucha sin descanso por la liberación animal.</p>

    <p class="lead">Nuestro objetivo es concientizar a las personas sobre la <strong><%= link_to 'grave problemática', earthlings_url, target: '_blank' %></strong> del uso animal y <a href='#diffusion'>lo que podemos hacer</a> al respecto.</p>

    <p class="lead">Además alentamos a aquellos que hayan tomado la decisión de hacerse veganos a involucrarse con la causa. ¡Los animales te necesitan!</p>

  </div>
  <div class="col-md-4">
    <%= image_tag 'profile.png', class: 'img-responsive thumbnail' %>
  </div>
</div>

app/views/application/home/_advocacy.html.erb
<header class="jumbotron">
  <h1><%= t :advocacy %></h1>
</header>

<div id="activities" class="row">

  <div class="col-md-4">
    <article class="well iconed">
      <header>
        <%= icon :bullhorn %>
        <h2><%= link_to t(:diffusion), '#diffusion'%></h2>
      </header>
      <p>Todos los viernes de 14 a 17:30 hs nos concentramos en la esquina de 7 y 50 para difundir el veganismo y los derechos de los animales.</p>
    </article>
  </div>

  <div class="col-md-4">
    <article class="well iconed">
      <header>
        <%= icon :cutlery %>
        <h2><%= link_to t(:cuisine), '#cuisine'%></h2>
      </header>
      <p>Brindamos talleres para enseñar que la comida vegana es fácil, rica y que está al alcance de todos. Podés anotarte mandando un mail a activismo.coala@gmail.com.</p>
    </article>
  </div>

  <div class="col-md-4">
    <article class="well iconed">
      <header>
        <%= icon :microphone %>
        <h2><%= link_to t(:radio), '#radio'%></h2>
      </header>
      <p>Nos podés escuchar todos los viernes de 18 a 20 hs por <strong>Radio Capital La Plata FM 95.5</strong>, en nuestro programa de radio "Abrazo Animal".</p>
      <p><%= link_to 'Visitanos por Facebook', 'https://www.facebook.com/abrazoanimal95.5' %>.</p>
    </article>
  </div>
</div>

app/views/application/home/_cover.html.erb
<%#= image_tag 'cover2b.jpg', class: 'img-responsive' %>
<%= image_tag 'cover.svg', class: 'img-responsive' %>

<article class="semi-transparent  iconed">
  <h1><%= t :brand_explanation %></h1>
  <%= link_to icon('angle-down'), '#about', class: 'btn btn-success' %>
</article>

app/views/application/home/_cuisine.html.erb
<header><h1><%= t :cuisine %></h1></header>

<div class="row">
  <div class="col-md-7">
<div class="transparent">
  <p>Nuestros talleres de <strong>Cocina Vegana</strong> son encuentros independientes, de una duración de aproximadamente 2 horas, donde enseñamos cómo preparar deliciosas comidas sin utilizar ningún ingrediente de origen animal.</p>
  
  <p>Son una gran oportunidad para acercarse al veganismo; conocer un poco más sobre la grave problemática del uso animal; y degustar y aprender a preparar comidas accesibles, fáciles y deliciosas.</p>

  <p>Los talleres son para cualquier persona (con o sin experiencia en la cocina). No es necesario llevar nada a los talleres, ya que nosotros nos encargamos de todos los materiales.</p>

  <p>El costo es a voluntad. Con el dinero recaudado, además de cubrir los gastos del taller, financiamos folletos y actividades para difundir nuestra lucha contra la discriminación y explotación de todos los animales. Todo nuestro trabajo es de forma voluntaria.</p>

  </div>
</div>

  <div class="col-md-5">
    <article class="radio">
      <%= icon('cutlery thumbnail') %>
    </article>
  </div>
</div>

app/views/application/home/_radio.html.erb
<header><h1><%= t :radio %></h1></header>

<div class="row">
  <div class="col-md-5">
    <article class="radio">
      <%= icon('microphone thumbnail') %>
    </article>
  </div>
  <div class="col-md-7">

    <p class="lead">Un espacio que generamos para debatir y compartir diferentes enfoques y miradas sobre temas que no suelen ser del conocimiento general</p>

    <p class="lead">La música que te gusta todos los viernes de <strong>18:00</strong> a <strong>20:00</strong> hs por <strong>Radio Capital FM 95.5</strong> La Plata - Buenos Aires</p>


    <p class="lead">Seguinos por <%= link_to 'nuestra página de facebook', 'https://www.facebook.com/abrazoanimal95.5', target: '_blank' %>.</p>

    <p class="lead">Si no sos de La Plata, podés <%= link_to 'escucharnos online', 'http://www.radiocapitallaplata.com.ar/', target: '_blank' %> todos los viernes entre las 18 y las 20 horas.</p>
  </div>
</div>

app/views/application/subscribe.html.erb
<section class="col-md-6 col-md-offset-3" style="margin-top: 3em;">

<h1 class="page-header"><%= t :subscription_to, event: @event.name %></h1>

<section class="well">
<%= form_for @form, url: submit_subscription_path do |f| %>

  <%= f.hidden_field :event_id %>

  <article class="form-group">
    <%= f.label :email %><br>
    <%= f.text_field :email, autofocus: true, class: 'form-control' %>
  </article>

  <article class="form-group">
    <%= f.label :first_name %><br>
    <%= f.text_field :first_name, class: 'form-control' %>
  </article>

  <article class="form-group">
    <%= f.label :last_name %><br>
    <%= f.text_field :last_name, class: 'form-control' %>
  </article>

  <article class="form-group">
    <%= submit_tag t(:submit), class: 'btn btn-primary' %>
  </article>
<% end %>

</section>

</section>

app/views/application/success.html.erb
<section class="col-md-6 col-md-offset-3" style="margin-top: 3em;">

  <h1 class="page-header"><%= t :success %></h1>

</section>

app/views/layouts/admin/admin.html.erb
<!DOCTYPE html>
<html lang="es">
  <head><%= render 'head' %></head>
  <body>
    <%= render 'navbar' %>
    <div id="main" class="container-fluid">
      <div class="row">
        <aside class="col-md-2">
          <%= render 'aside' %>
        </aside>
        <section class="col-md-10">
          <%= yield %>
        </section>
      </div>
    </div>
    <%= flash_messages if flash %>
  </body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="es">
  <head><%= render 'head' %></head>
  <body data-spy="scroll" data-target=".scrollspy">
    <%= yield %>

    <footer id="footer" class="home-section">
      <div class="container"><p><%= t :brand_explanation %> - <%= Date.today.year %></p></div>
    </footer>
  </body>
</html>

app/views/layouts/simple.html.erb
<!DOCTYPE html>
<html lang="es">
  <head><%= render 'admin/admin/head' %></head>
  <body>
    <div id="main" class="container-fluid">
      <%= yield %>
    </div>
    <%= flash_messages if flash %>
  </body>
</html>